"""Reading manufacturing-relevant facts out of a solid.

This is the part that makes a DFM checker more than a spreadsheet. The
sheet-metal rules in project 05 check *parameters* -- numbers the designer
hands over -- and that only works when the design was generated by the same
code doing the checking. A real DFM check reads a STEP file it did not
create, from a supplier or another team, and finds out what is in it.

Everything here interrogates B-rep geometry:

  * face type and orientation, so a cylinder can be told from a plane and
    an internal fillet from an external round;
  * outward surface normals, which requires respecting face orientation --
    OpenCASCADE stores a reversed face with its natural normal pointing
    *into* the solid, and forgetting that inverts every draft angle;
  * ray casting through the solid, which is how wall thickness is actually
    measured rather than assumed.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from OCC.Core.BRepAdaptor import BRepAdaptor_Surface
from OCC.Core.BRepGProp import BRepGProp_Face, brepgprop
from OCC.Core.BRepIntCurveSurface import BRepIntCurveSurface_Inter
from OCC.Core.BRepTools import breptools
from OCC.Core.GeomAbs import (
    GeomAbs_Cone,
    GeomAbs_Cylinder,
    GeomAbs_Plane,
    GeomAbs_Sphere,
    GeomAbs_Torus,
)
from OCC.Core.GProp import GProp_GProps
from OCC.Core.TopAbs import TopAbs_FACE
from OCC.Core.TopExp import TopExp_Explorer
from OCC.Core.TopoDS import topods
from OCC.Core.gp import gp_Dir, gp_Lin, gp_Pnt, gp_Vec

SURFACE_NAMES = {
    GeomAbs_Plane: "plane",
    GeomAbs_Cylinder: "cylinder",
    GeomAbs_Cone: "cone",
    GeomAbs_Sphere: "sphere",
    GeomAbs_Torus: "torus",
}


@dataclass(frozen=True)
class FaceInfo:
    """One face, with the facts a manufacturing check needs."""

    index: int
    kind: str
    area_mm2: float
    centroid: tuple[float, float, float]
    outward_normal: tuple[float, float, float]
    radius_mm: float | None = None      # cylinders and cones only
    concave: bool | None = None         # cylinders: pocket wall vs boss

    @property
    def diameter_mm(self) -> float | None:
        return None if self.radius_mm is None else 2 * self.radius_mm


def faces(shape) -> list:
    out, explorer = [], TopExp_Explorer(shape, TopAbs_FACE)
    while explorer.More():
        out.append(topods.Face(explorer.Current()))
        explorer.Next()
    return out


def face_area_mm2(face) -> float:
    props = GProp_GProps()
    brepgprop.SurfaceProperties(face, props)
    return props.Mass()


def outward_normal(face, u: float, v: float) -> tuple[float, float, float]:
    """Unit normal pointing *out of* the material at (u, v).

    `BRepGProp_Face.Normal` already accounts for face orientation, and it
    is worth stating because the obvious defensive move is wrong. This
    function originally flipped the vector itself whenever the face was
    TopAbs_REVERSED, on the reasoning that OpenCASCADE stores a reversed
    face with its parametric normal pointing into the solid. Checking it
    against a known part settled the question: on the actuator's cylinder
    body the two bores are reversed faces, and their raw normals already
    point toward the axis -- outward from the material, which is correct.
    Flipping them again turned both bores into bosses.

    So: no flip. The check that caught it is
    `test_bores_and_bosses_are_told_apart` in test_dfm.py.
    """
    point, vector = gp_Pnt(), gp_Vec()
    BRepGProp_Face(face).Normal(u, v, point, vector)
    if vector.Magnitude() < 1e-12:
        raise ValueError("degenerate surface normal")
    vector.Normalize()
    return (vector.X(), vector.Y(), vector.Z())


def face_midpoint_uv(face) -> tuple[float, float]:
    u_min, u_max, v_min, v_max = breptools.UVBounds(face)
    return (u_min + u_max) / 2.0, (v_min + v_max) / 2.0


def point_at(face, u: float, v: float) -> tuple[float, float, float]:
    point, vector = gp_Pnt(), gp_Vec()
    BRepGProp_Face(face).Normal(u, v, point, vector)
    return (point.X(), point.Y(), point.Z())


def _is_concave_cylinder(face, adaptor) -> bool:
    """Does this cylindrical face curve around a hole, or around a boss?

    Compare the outward normal at the face midpoint against the direction
    from the cylinder axis to that point. They agree on a boss, where
    material is inside the surface, and oppose on a bore, where the
    material is outside it. That single test is what separates a hole to be
    drilled from a shaft to be turned.
    """
    u, v = face_midpoint_uv(face)
    normal = outward_normal(face, u, v)
    point = point_at(face, u, v)
    axis = adaptor.Cylinder().Axis()
    origin = axis.Location()
    direction = axis.Direction()

    to_point = [point[i] - c for i, c in enumerate(
        (origin.X(), origin.Y(), origin.Z()))]
    axis_vec = (direction.X(), direction.Y(), direction.Z())
    along = sum(to_point[i] * axis_vec[i] for i in range(3))
    radial = [to_point[i] - along * axis_vec[i] for i in range(3)]
    length = math.sqrt(sum(c * c for c in radial))
    if length < 1e-9:
        return False
    radial = [c / length for c in radial]
    return sum(radial[i] * normal[i] for i in range(3)) < 0.0


def describe_faces(shape) -> list[FaceInfo]:
    """Every face, typed and measured."""
    described = []
    for index, face in enumerate(faces(shape)):
        adaptor = BRepAdaptor_Surface(face)
        kind = SURFACE_NAMES.get(adaptor.GetType(), "other")
        u, v = face_midpoint_uv(face)
        try:
            normal = outward_normal(face, u, v)
        except ValueError:
            continue
        radius = concave = None
        if adaptor.GetType() == GeomAbs_Cylinder:
            radius = adaptor.Cylinder().Radius()
            concave = _is_concave_cylinder(face, adaptor)
        described.append(FaceInfo(
            index=index, kind=kind, area_mm2=face_area_mm2(face),
            centroid=point_at(face, u, v), outward_normal=normal,
            radius_mm=radius, concave=concave))
    return described


def ray_thickness_mm(shape, origin, direction, max_length: float = 1e4):
    """Material thickness from a surface point, inward along `direction`.

    Fires a ray and returns the distance to the first surface it meets
    after leaving the start point. On a wall that is the far side of the
    wall, so the distance is the wall thickness -- measured, not declared.

    Returns None when the ray escapes without hitting anything, which
    happens on a convex outer surface fired outward and is a legitimate
    answer rather than an error.
    """
    line = gp_Lin(gp_Pnt(*origin), gp_Dir(*direction))
    intersector = BRepIntCurveSurface_Inter()
    intersector.Init(shape, line, 1e-6)

    nearest = None
    while intersector.More():
        distance = intersector.W()
        # Skip the face the ray started on. 1e-4 mm is far below any real
        # feature and far above the tolerance the intersector works to.
        if 1e-4 < distance < max_length:
            nearest = distance if nearest is None else min(nearest, distance)
        intersector.Next()
    return nearest
